[programs.devnet]
distribute_token_solana = "5M7Ny1BpnSHrXNoHzb8tqgPJ5RTFH9twXzfQkrSscuh5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/vuhuynh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
