[programs.localnet]
distribute_token_solana = "GLfs2uXqmGoun5X4eTVxS7TcRPqw5dnsWvtEPzJzAq4v"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/vuhuynh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
